version: "3.9"
services:
  web:
    build: .
    ports:
      - "8093:80"
    env_file: .env
    labels:
      traefik.enable: "true"
      traefik.http.routers.smallgroup.rule: "Host(`rr.${DOMAIN}`)"
      traefik.http.routers.smallgroup.tls.certresolver: "letsencrypt"
      traefik.http.routers.smallgroup.tls.domains[0].main: "${DOMAIN}"
      traefik.http.routers.smallgroup.tls.domains[0].sans: "*.${DOMAIN}"
      traefik.http.services.smallgroup.loadbalancer.server.port: "80"
